<?
/**
 * @var $this \Zend\View\Renderer\PhpRenderer
 * @var $form \User\Form\Register
 */
?>

<?= $this->form()->openTag($form->prepare()); ?>
    <?= $this->partial('generic/form/element.phtml', array('element' => $form->get('email'))); ?>
    <div class="form-actions">
        <input type="submit" name="submit" value="Сменить пароль" class="btn green" />
        <a href="<?= $this->url('home') ?>" class="btn red">Отмена</a>
    </div>
<?= $this->form()->closeTag(); ?>