<?
/**
 * @var $this \Zend\View\Renderer\PhpRenderer
 * @var $teams \Brainworkers\Entity\Team[]
 * @var $questions \Brainworkers\Entity\Question[]
 */
?>
<a id="toggle" class="btn blue" href="javascript:void(0)" data-state="global" data-place-id="<?=$this->ZfcUserIdentity() ? $this->ZfcUserIdentity()->getPlace() ? $this->ZfcUserIdentity()->getPlace()->getId() : 0 : 0;?>">Глобальные результаты</a>
<table class="table table-striped table-bordered table-advance table-hover" id="results">
    <thead>
    <tr>
        <th>Название команды</th>
        <th>Город</th>
        <th>Повопросная таблица</th>
        <th>Ответов (сумма)</th>
        <th>Место</th>
    </tr>
    </thead>
    <tbody>
    <? foreach ($teams as $n => $team): ?>
        <tr data-place-id="<?=$team->getPlace() ? $team->getPlace()->getId() : 0;?>">
            <td><?=$team->getName()?></td>
            <td><?=$team->getCity() ? $team->getCity()->getName() : ''?></td>
            <td>
                <?
                $rounds = array(); $round = 0;
                $answers = $team->getAnswers();
                foreach($questions as $k => $question) {
                    if ($k % 15 == 0) {
                        $round++;
                    }
                    $rounds[$round][] = $answers->containsKey($k) ? $answers->get($k)->getResolution() : 0;
                }
                ?>

                <? foreach ($rounds as $r => $values): ?>
                    <a title="<?=implode(' ', $values)?>" href="javascript:void(0)" data-toggle="tooltip">
                        <span class="badge badge-info"><?=array_sum($values)?></span>
                    </a>
                <? endforeach;?>
            </td>
            <td><?=$team->getAnswers()->count()?></td>
            <td>
                <?=$n+1?>
            </td>
        </tr>
    <? endforeach; ?>
    </tbody>
</table>


<? $this->headScript()->captureStart() ?>
//<script type="text/javascript">
    (function() {
        $('#toggle').click(function() {
            if ($(this).data('state') == 'global') {
                $(this).data('state', 'local').text('Локальные результаты');
                $('tbody tr[data-place-id!="' + $(this).data('place-id') + '"]').hide();
            } else {
                $(this).data('state', 'global').text('Глобальные результаты');
                $('#results tbody tr').show();
            }
        });

        $('*[data-toggle="tooltip"]').tooltip({
            trigger: 'click'
        });
    })();
//</script>
<? $this->headScript()->captureEnd() ?>