<? $this->navigation('navigation')->getContainer()->findBy('uri', '/about')->setActive(); ?>

<table class="table table-striped table-bordered table-advance table-hover">
<tr>
<td class="span3"><img src="/photo/giryaev.jpg" /></td>
<td>
<b>Денис Гиряев</b><br />
<span class="label label-info">Руководитель проекта</span><br />
<span class="label label-success"><i class="icon-map-marker"></i> Витебск</span><br />

Автор и ведущий ряда интернет-проектов: <a href="http://edutoday.ru/" target="_blank">EduToday</a>, EduCast, Паутина, РУнетим.Шоу и других. Блогер. 
</td>
</tr>

<tr>
<td class="span3"><img src="/photo/drouz.jpg" /></td>
<td>
<b>Александр Друзь</b><br />
<span class="label label-info">Ведущий</span><br />
<span class="label label-success"><i class="icon-map-marker"></i> Санкт-Петербург</span><br />
Знаток элитарного клуба «Что? Где? Когда?», магистр игры «Что? Где? Когда?» и обладатель Бриллиантовой и шести Хрустальных сов, трёхкратный Чемпион Мира по игре «Что? Где? Когда?».
</td>
</tr>

<tr>
<td class="span3"><img src="/photo/skipsky.jpg" /></td>
<td>
<b>Михаил Скипский</b><br />
<span class="label label-info">Редактор 1 тура</span><br />
<span class="label label-success"><i class="icon-map-marker"></i> Санкт-Петербург</span><br />
Знаток элитарного клуба «Что? Где? Когда?», обладатель «Хрустальной совы» (2010), в 2008 году удостоен премии МАК в номинации «Тренер». В спортивной версии игры выступает в основном в составах команд «ЮМА» и «Город утрат».
</td>
</tr>

<tr>
<td class="span3"><img src="/photo/ivanov.jpg" /></td>
<td>
<b>Михаил Иванов</b><br />
<span class="label label-info">Редактор 2 тура</span><br />
<span class="label label-success"><i class="icon-map-marker"></i> Волгоград</span><br />
Сертифицированный редактор МАК
</td>
</tr>

<tr>
<td class="span3"><img src="/photo/efimov.jpg" /></td>
<td>
<b>Сергей Ефимов</b><br />
<span class="label label-info">Редактор 3 тура</span><br />
<span class="label label-success"><i class="icon-map-marker"></i> Саратов</span><br />
Сертифицированный редактор МАК

</td>
</tr>

<tr>
<td class="span3"><img src="/photo/korobejn.jpg" /></td>
<td>
<b>Александр Коробейников</b><br />
<span class="label label-info">Редактор 3 тура</span><br />
<span class="label label-success"><i class="icon-map-marker"></i> Санкт-Петербург</span><br />
Сертифицированный редактор МАК
</td>
</tr>

<tr>
<td class="span3"><img src="/photo/nikolenko.jpg" /></td>
<td>
<b>Сергей Николенко</b><br />
<span class="label label-info">Редактор 4 тура, топ-редактор</span><br />
<span class="label label-success"><i class="icon-map-marker"></i> Санкт-Петербург</span><br />
Знаток элитарного клуба «Что? Где? Когда?», сертифицированный редактор МАК
</td>
</tr>

<tr>
<td class="span3"><img src="/photo/supranovich.jpg" /></td>
<td>
<b>Андрей Супранович</b><br />
<span class="label label-info">Руководитель жюри</span><br />
<span class="label label-success"><i class="icon-map-marker"></i> Москва</span><br />
Знаток элитарного клуба «Что? Где? Когда?», сертифицированный арбитр МАК
</td>
</tr>

<tr>
<td class="span3"><img src="/photo/tupitsina.jpg" /></td>
<td>
<b>Екатерина Тупицына</b><br />
<span class="label label-info">Редактор сайта и документации</span><br />
<span class="label label-success"><i class="icon-map-marker"></i> Новосибирск</span><br />
Поэт, писатель. Играет в спортивное «Что? Где? Когда?» 5 лет.
</td>
</tr>

<tr>
<td class="span3"><img src="/photo/shohova.jpg" /></td>
<td>
<b>Евгения Шохова</b><br />
<span class="label label-info">Ответственная за работу с авторами вопросов и редакторами</span><br />
<span class="label label-success"><i class="icon-map-marker"></i> Одесса</span><br />
Тренер школьных команд по игре «Что? Где? Когда?».
</td>
</tr>

<tr>
<td class="span3"><img src="/photo/shabanov.jpg" /></td>
<td>
<b>Дмитрий Шабанов</b><br />
<span class="label label-info">Программист</span><br />
<span class="label label-success"><i class="icon-map-marker"></i> Санкт-Петербург</span><br />

</td>
</tr>
</table>
