<? if ($this->isAllowed('live')): ?>
<? $this->navigation('navigation')->getContainer()->findBy('uri', '/live')->setActive(); ?>
<div class="row-fluid">
	<div class="span12">
		<h4>Трансляция</h4>
<!--		<iframe width="100%" height="90" src="http://www.youtube.com/embed/jyR0uMCHajw?feature=player_detailpage" frameborder="0" allowfullscreen></iframe>-->
        <iframe width="420" height="315" src="http://www.youtube.com/embed/cxvpYZGN0Uo" frameborder="0"></iframe>
<!-- Put this script tag to the <head> of your page -->
        <script type="text/javascript" src="//vk.com/js/api/openapi.js?93"></script>

        <script type="text/javascript">
            VK.init({apiId: 3602019, onlyWidgets: true});
        </script>

<!-- Put this div tag to the place, where the Comments block will be -->
        <div id="vk_comments"></div>
        <script type="text/javascript">
            VK.Widgets.Comments("vk_comments", {limit: 10, width: "520", attach: "*"});
        </script>
	</div>
<!--	<div class="span5">-->
<!--		<h4>Текущий вопрос: <b>№14</b></h4>-->
<!--		<h4>Таймер</h4>-->
<!--		<div id="fancyClock"></div>-->
<!--	</div>-->
<!--	<div class="span6">-->
<!--		<h4>Текущая раздатка</h4>-->
<!--	</div>-->
</div>
<? endif; ?>