<? $this->navigation('navigation')->getContainer()->findBy('uri', '/live')->setActive(); ?>
<div class="row-fluid">
	<div class="span12">
		<h4>Трансляция</h4>
<!--		<iframe width="100%" height="90" src="http://www.youtube.com/embed/jyR0uMCHajw?feature=player_detailpage" frameborder="0" allowfullscreen></iframe>-->
        <iframe width="420" height="315" src="http://www.youtube.com/embed/cxvpYZGN0Uo" frameborder="0"></iframe>
	</div>
<!--	<div class="span5">-->
<!--		<h4>Текущий вопрос: <b>№14</b></h4>-->
<!--		<h4>Таймер</h4>-->
<!--		<div id="fancyClock"></div>-->
<!--	</div>-->
<!--	<div class="span6">-->
<!--		<h4>Текущая раздатка</h4>-->
<!--	</div>-->
</div>