<?
/**
 * @var $this \Zend\View\Renderer\PhpRenderer
 * @var $places \Brainworkers\Entity\Place[]
 */
?>

<div class="row-fluid">
    <div class="span12">
        <table class="table table-striped table-bordered table-advance table-hover" id="teams-table">
            <thead>
            <tr>
                <th>Страна</th>
                <th>Город</th>
                <th>Команды</th>
                <th>Представитель</th>
                <th class="span7">Действия</th>
            </tr>
            </thead>
            <tfoot>
            <tr>
                <td colspan="7">
                    <a class="btn green" href="<?=$this->url('place/add')?>">
                        <i class="icon-plus-sign icon-white"></i>
                        Добавить Площадку
                    </a>
                </td>
            </tr>
            </tfoot>
            <tbody>
            <? foreach($places as $place): ?>
                <tr>
                    <td><?=$place->getCity() && $place->getCity()->getCountry() ? $place->getCity()->getCountry()->getName() : ''?></td>
                    <td><?=$place->getCity() ? $place->getCity()->getName() : ''?></td>
                    <td><?=$place->getTeams()->count()?> / <?=$place->getTeamsMax()?></td>
                    <td><?=$place->getOwner() ? $place->getOwner()->getDisplayName() : ''?></td>
                    <td>
                        <? if ($this->isAllowed('place', 'list')): ?>
                            <a class="btn blue" href="<?=$this->url('place/show', array('id' => $place->getId()))?>">
                                <i class="icon-book"></i>
                                Профиль
                            </a>
                        <? endif; ?>
                    </td>
                </tr>
            <? endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<? $this->headLink()->appendStylesheet($this->basePath('assets/data-tables/DT_bootstrap.css')) ?>
<? $this->headScript()->appendFile($this->basePath('assets/data-tables/jquery.dataTables.js')) ?>
<? $this->headScript()->appendFile($this->basePath('assets/data-tables/DT_bootstrap.js')) ?>
<? $this->headScript()->appendFile($this->basePath('js/jquery/data-tables/datatables.js')) ?>

<? $this->headScript()->captureStart() ?>
//<script type="text/javascript">
    (function() {
        $('#teams-table').dataTable();
    })();
//</script>
<? $this->headScript()->captureEnd() ?>