<?
/**
 * @var $this \Zend\View\Renderer\PhpRenderer
 * @var $places \Brainworkers\Entity\Place[]
 */
?>

<div class="row-fluid">
    <div class="span12">
        <table class="table table-striped table-bordered table-advance table-hover" id="teams-table">
            <thead>
            <tr>
                <th>ID</th>
                <th>Страна</th>
                <th>Город</th>
                <th>Команды</th>
                <th>Представитель</th>
                <th class="span3">Действия</th>
            </tr>
            </thead>
            <tfoot>
            <tr>
                <td colspan="8">
                    <a class="btn green" href="<?=$this->url('place/add')?>">
                        <i class="icon-plus-sign icon-white"></i>
                        Добавить Площадку
                    </a>
                </td>
            </tr>
            </tfoot>
            <tbody>

            </tbody>
        </table>
    </div>
</div>

<? $this->headLink()->appendStylesheet($this->basePath('assets/data-tables/DT_bootstrap.css')) ?>
<? $this->headScript()->appendFile($this->basePath('assets/data-tables/jquery.dataTables.js')) ?>
<? $this->headScript()->appendFile($this->basePath('assets/data-tables/DT_bootstrap.js')) ?>
<? $this->headScript()->appendFile($this->basePath('js/jquery/data-tables/datatables.js')) ?>

<? $this->headScript()->captureStart() ?>
//<script type="text/javascript">
    (function() {
        $('#teams-table').dataTable({
            sDom: "<'row-fluid'<'span6'l><'span6'>r>t<'row-fluid'<'span6'i><'span6'p>>",
            aaSorting: [[0, 'desc']],
            bStateSave: true,
            bProcessing: true,
            bSearchable: false,
            bServerSide: true,
            sAjaxSource: '<?=$this->url('place/list')?>',
            sAjaxDataProp: 'places',
            sServerMethod: 'POST',
            aoColumns: [
                {
                    mDataProp: 'id',
                    bVisible: false
                },
                {
                    mDataProp: 'country_name'
                },
                {
                    mDataProp: 'city_name'
                },
                {
                    mDataProp: 'team'
                },
                {
                    mDataProp: 'user_name'
                },
                {
                    mData: function(obj, type) {
                        return '<a class="btn blue" href="<?=$this->url('place/show', array('id' => ''))?>' + obj.id + '"><i class="icon-book"></i> Профиль</a>';
                    },
                    bSortable: false
                }

            ]
        });
    })();
//</script>
<? $this->headScript()->captureEnd() ?>