<?
/**
 * @var $this \Zend\View\Renderer\PhpRenderer
 * @var $place \Brainworkers\Entity\Place
 */
?>

<p><?=$place->getCountryName()?>, <?=$place->getCityName()?></p>
<p>Команд: <?=$place->getTeams()->count()?> / <?=$place->getTeamsMax()?></p>
<p>Точный адрес места проведения: <?=$place->getAddress()?></p>
<p>Дополнительный взнос на площадке: <?=$place->getAddMoney() ?: 'Нет' ?></p>
<p>Видеосъемка: <?=$place->getVideoStateText()?></p>
<p>Событие ВКонтакте: <?=$place->getEventVk()?></p>

<p>Команды:</p>
<table class="table table-striped table-bordered table-advance table-hover">
    <thead>
    <tr>
        <th>№</th>
        <th>Название</th>
        <th>ФИО капитана</th>
        <th>Оплачено?</th>
    </tr>
    </thead>
    <tbody>
    <? if ($place->getTeams()->count() > 0): ?>
        <? foreach ($place->getTeams() as $team): ?>
            <tr>
                <td><?=$team->getLocalId()?></td>
                <td><?=$team->getName()?></td>
                <td><?=$team->getCaptain()->first()?></td>
                <td><?=$team->getPayed() ? 'Да' : 'Нет'?></td>
            </tr>
        <? endforeach; ?>
    <? else:?>
        <tr>
            <td class="text-center" colspan="3">Нет команд</td>
        </tr>
    <? endif;?>
    </tbody>
</table>

<p>
    <? if ($this->isAllowed('team', 'assign') && $this->ZfcUserIdentity() && !$place->getTeams()->contains($this->ZfcUserIdentity()->getTeams()->first())): ?>
        <a class="btn green" href="<?=$this->url('team/assign-to', array('placeId' => $place->getId()))?>">
            <i class="icon-plus icon-white"></i>
            Привязать
        </a>
    <? endif; ?>

    <? if ($this->isAllowed('place', 'edit') || ($place->getOwner() && $this->ZfcUserIdentity() && $place->getOwner()->getId() == $this->ZfcUserIdentity()->getId())): ?>
        <a class="btn blue" href="<?=$this->url('place/edit', array('id' => $place->getId()))?>">
            <i class="icon-edit"></i>
            Редактировать
        </a>
    <? endif; ?>

    <? if ($this->isAllowed('place', 'delete') || ($place->getOwner() && $this->ZfcUserIdentity() && $place->getOwner()->getId() == $this->ZfcUserIdentity()->getId())): ?>
        <a onclick="return confirm('Really?')" class="btn red" href="<?=$this->url('place/delete', array('id' => $place->getId()))?>">
            <i class="icon-minus-sign icon-white"></i>
            Удалить
        </a>
    <? endif; ?>
</p>