<? $this->placeholder('body-class')->set("login"); ?>
<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
?>

  <!-- BEGIN LOGIN -->
  <div class="content">
    <!-- BEGIN LOGIN FORM -->
	<?php echo $this->form()->openTag($form) ?>
      <h3 class="form-title">Войти в аккаунт</h3>
      <div class="control-group">
        <div class="controls">
          <div class="input-icon left">
            <i class="icon-user"></i>
            <input class="m-wrap" name="identity" type="text" placeholder="Электронная почта" />
          </div>
        </div>
      </div>
      <div class="control-group">
        <div class="controls">
          <div class="input-icon left">
            <i class="icon-lock"></i>
            <input class="m-wrap" name="credential"type="password" style="" placeholder="Пароль" />
          </div>
        </div>
      </div>
      <div class="form-actions">
        <label class="checkbox">
            <input type="hidden" name="remember" value="0">
            <input type="checkbox" name="remember" value="1">
            Запомнить меня
        </label>
		<button class="btn green pull-right" type="submit" name="submit" value="">Войти <i class="m-icon-swapright m-icon-white"></i></button>
        
      </div>
      <div class="forget-password">
        <h4>Forgot your password ?</h4>
        <p>
          no worries, click <a href="<?=$this->url('user/reset-password')?>" class="" id="forget-password">here</a>
          to reset your password.
        </p>
      </div>
	<?php echo $this->form()->closeTag() ?>
    <!-- END LOGIN FORM -->        
  </div>
  <!-- END LOGIN -->
  <script src="assets/js/jquery-1.8.3.min.js"></script>
  <script src="assets/bootstrap/js/bootstrap.min.js"></script>  
  <script src="assets/uniform/jquery.uniform.min.js"></script> 
  <script src="assets/js/jquery.blockui.js"></script>
  <script src="assets/js/app.js"></script>
  <script>
    jQuery(document).ready(function() {     
      App.initLogin();
    });
  </script>
