<? /** @var $collection \Zend\Form\Element\Collection */ ?>

<? if ($collection instanceof \Zend\Form\Element\Collection): ?>

    <fieldset name="<?= $collection->getName() ?>">
    <legend>
        <?=$collection->getLabel()?>
        <? if ($collection->shouldCreateTemplate()): ?>
            <a data-template-for="<?= $collection->getName() ?>"
               class="template-remove btn red-stripe pull-right"
               href="javascript:void(0)"
            ><i class="icon-minus-sign"></i></a>
            <a data-template-for="<?= $collection->getName() ?>"
               data-template-key="<?= $collection->getTemplatePlaceholder() ?>"
               class="template-add btn green-stripe pull-right"
               href="javascript:void(0)"
            ><i class="icon-plus-sign"></i></a>
        <? endif; ?>
    </legend>

    <div class="row-fluid">
<? endif; ?>

<?php
foreach ($collection as $element) {
    if ($element instanceof \Zend\Form\Element\Collection) {
        echo $this->partial('generic/form/collection.phtml', array('collection' => $element));
        if ($element->shouldCreateTemplate()) {
            echo'<span data-for="' . $element->getName() . '" data-template="' . $this->escapeHtmlAttr(
                $this->partial('generic/form/collection.phtml', array('collection' => $element->getTemplateElement()))
            ) . '"></span>';
        }
    } else {
        if ($element instanceof \Zend\Form\Fieldset) {
            echo $this->partial('generic/form/fieldset.phtml', array('collection' => $element, 'class' => 'span3'));
        } else {
            echo $this->partial('generic/form/element.phtml', array('element' => $element));
        }
    }
}
?>

</div>
