<?
/**
 * @var $this \Zend\View\Renderer\PhpRenderer
 * @var $teams \Brainworkers\Entity\Team[]
 */
?>

<div class="row-fluid">
    <div class="span12">

        <? if ($this->ZfcUserIdentity() && count($this->ZfcUserIdentity()->getTeams()) >= 1): ?>
            <div class="hero-unit">
                <h2>Ваша Команда</h2>

                <? foreach($this->ZfcUserIdentity()->getTeams() as $team): ?>
                    <? /** @var $team \Brainworkers\Entity\Team */ ?>
                    <p><?=$team->getName()?>, <?=$team->getCaptain()->first()?></p>

                    <? if($team->getPlace()): ?>
                        <p>Площадка: <?=$team->getPlace()->getAddress()?></p>
                    <? else: ?>
                        <p>Не привязана к площадке</p>
                    <? endif; ?>

                    <? if($team->getPayed()): ?>
                        <p>Оплачено</p>
                    <? else: ?>
                        <p>Не оплачено</p>
                    <? endif; ?>

                    <div class="row-fluid">
                        <? if ($this->isAllowed('team', 'list')): ?>
                            <a class="btn blue" href="<?=$this->url('team/show', array('id' => $team->getId()))?>">
                                Профиль
                            </a>
                        <? endif; ?>

                        <? if (!$team->getPayed()): ?>
                            <?=$this->render('generic/payment/team.phtml')?>
                        <? endif; ?>

                        <? if ($this->isAllowed('team', 'edit') || ($team->getOwner() && $team->getOwner()->getId() == $this->ZfcUserIdentity()->getId())): ?>
                            <a class="btn blue" href="<?=$this->url('team/edit', array('id' => $team->getId()))?>">
                                <i class="icon-edit"></i>
                                Редактировать
                            </a>
                        <? endif; ?>

                        <? if ($this->isAllowed('team', 'delete') || ($team->getOwner() && $team->getOwner()->getId() == $this->ZfcUserIdentity()->getId())): ?>
                            <a onclick="return confirm('Really?')" class="btn red" href="<?=$this->url('team/delete', array('id' => $team->getId()))?>">
                                <i class="icon-minus-sign icon-white"></i>
                                Удалить
                            </a>
                        <? endif; ?>
                    </div>
                <? endforeach; ?>
            </div>
        <? endif; ?>

        <table class="table table-striped table-bordered table-advance table-hover" id="teams-table">
            <thead>
            <? if ($this->isAllowed('team', 'add') && $this->ZfcUserIdentity() && count($this->ZfcUserIdentity()->getTeams()) < 1): ?>
            <tr>
                <td colspan="6">
                    <a class="btn green" href="<?=$this->url('team/add')?>">
                        <i class="icon-plus-sign icon-white"></i>
                        Добавить команду
                    </a>
                </td>
            </tr>
            <? endif; ?>
            <tr>
                <th>ID</th>
                <th>Название</th>
                <th>Страна</th>
                <th>Город</th>
                <th>Капитан</th>
                <th>Оплачено</th>
                <th class="span3">Действия</th>
            </tr>
            </thead>
            <? if ($this->isAllowed('team', 'add') && $this->ZfcUserIdentity() && count($this->ZfcUserIdentity()->getTeams()) < 1): ?>
            <tfoot>
            <tr>
                <td colspan="6">
                    <a class="btn green" href="<?=$this->url('team/add')?>">
                        <i class="icon-plus-sign icon-white"></i>
                        Добавить команду
                    </a>
                </td>
            </tr>
            </tfoot>
            <? endif; ?>
            <tbody>
            </tbody>
        </table>
    </div>
</div>

<? $this->headLink()->appendStylesheet($this->basePath('assets/data-tables/DT_bootstrap.css')) ?>
<? $this->headScript()->appendFile($this->basePath('assets/data-tables/jquery.dataTables.js')) ?>
<? $this->headScript()->appendFile($this->basePath('assets/data-tables/DT_bootstrap.js')) ?>
<? $this->headScript()->appendFile($this->basePath('js/jquery/data-tables/datatables.js')) ?>

<? $this->headScript()->captureStart() ?>
//<script type="text/javascript">
    (function() {
        $('#teams-table').dataTable({
            sDom: "<'row-fluid'<'span6'l><'span6'>r>t<'row-fluid'<'span6'i><'span6'p>>",
            aaSorting: [[0, 'desc']],
            bProcessing: true,
            bStateSave: true,
            bSearchable: false,
            bServerSide: true,
            sAjaxSource: '<?=$this->url('team/list')?>',
            sAjaxDataProp: 'teams',
            sServerMethod: 'POST',
            aoColumns: [
                {
                    mDataProp: 'id',
                    bVisible: false
                },
                {
                    mDataProp: 'team_name'
                },
                {
                    mDataProp: 'country_name'
                },
                {
                    mDataProp: 'city_name'
                },
                {
                    mDataProp: 'captain_name'
                },
                {
                    mDataProp: 'payed',
                    mData: function(obj, type) {
                        return obj.payed ? 'Да' : 'Нет';
                    }
                },
                {
                    mData: function(obj, type) {
                        return '<a class="btn blue" href="<?=$this->url('team/show', array('id' => ''))?>' + obj.id + '"><i class="icon-book"></i> Профиль</a>';
                    },
                    bSortable: false
                }

            ]
        });
    })();
//</script>
<? $this->headScript()->captureEnd() ?>