<?
/**
 * @var $this \Zend\View\Renderer\PhpRenderer
 * @var $teams \Brainworkers\Entity\Team[]
 */
?>

<div class="row-fluid">
    <div class="span12">
        <table class="table table-striped table-bordered table-advance table-hover" id="teams-table">
            <thead>
            <? if ($this->isAllowed('team', 'add') && $this->ZfcUserIdentity() && count($this->ZfcUserIdentity()->getTeams()) < 1): ?>
            <tr>
                <td colspan="6">
                    <a class="btn green" href="<?=$this->url('team/add')?>">
                        <i class="icon-plus-sign icon-white"></i>
                        Добавить команду
                    </a>
                </td>
            </tr>
            <? endif; ?>
            <tr>
                <th>ID</th>
                <th>Название</th>
                <th>Страна</th>
                <th>Город</th>
                <th>Капитан</th>
                <th class="span5">Действия</th>
            </tr>
            </thead>
            <? if ($this->isAllowed('team', 'add') && $this->ZfcUserIdentity() && count($this->ZfcUserIdentity()->getTeams()) < 1): ?>
            <tfoot>
            <tr>
                <td colspan="6">
                    <a class="btn green" href="<?=$this->url('team/add')?>">
                        <i class="icon-plus-sign icon-white"></i>
                        Добавить команду
                    </a>
                </td>
            </tr>
            </tfoot>
            <? endif; ?>
            <tbody>
            <? foreach($teams as $team): ?>
                <tr>
                    <td><?=$team->getId()?></td>
                    <td><?=$team->getName()?></td>
                    <td><?=$team->getCountry() ? $team->getCountry()->getName() : ''?></td>
                    <td><?=$team->getCity() ? $team->getCity()->getName() : ''?></td>
                    <td><?=$team->getCaptain()->first()?></td>
                    <td>
                        <? if ($this->isAllowed('team', 'list')): ?>
                            <a class="btn blue" href="<?=$this->url('team/show', array('id' => $team->getId()))?>">
                                Профиль
                            </a>
                        <? endif; ?>

                        <? if ($this->isAllowed('team', 'edit') || ($team->getOwner() && $team->getOwner()->getId() == $this->ZfcUserIdentity()->getId())): ?>
                            <a class="btn blue" href="<?=$this->url('team/edit', array('id' => $team->getId()))?>">
                                <i class="icon-edit"></i>
                                Редактировать
                            </a>
                        <? endif; ?>

                        <? if ($this->isAllowed('team', 'delete') || ($team->getOwner() && $team->getOwner()->getId() == $this->ZfcUserIdentity()->getId())): ?>
                            <a onclick="return confirm('Really?')" class="btn red" href="<?=$this->url('team/delete', array('id' => $team->getId()))?>">
                                <i class="icon-minus-sign icon-white"></i>
								Удалить
                            </a>
                        <? endif; ?>
                    </td>
                </tr>
            <? endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<? $this->headLink()->appendStylesheet($this->basePath('assets/data-tables/DT_bootstrap.css')) ?>
<? $this->headScript()->appendFile($this->basePath('assets/data-tables/jquery.dataTables.js')) ?>
<? $this->headScript()->appendFile($this->basePath('assets/data-tables/DT_bootstrap.js')) ?>
<? $this->headScript()->appendFile($this->basePath('js/jquery/data-tables/datatables.js')) ?>

<? $this->headScript()->captureStart() ?>
//<script type="text/javascript">
    (function() {
        $('#teams-table').dataTable();
    })();
//</script>
<? $this->headScript()->captureEnd() ?>