<?
/**
 * @var $this \Zend\View\Renderer\PhpRenderer
 * @var $users \User\Entity\User[]
 */
?>

<div class="row-fluid">
    <div class="span12">
        <table class="table table-striped table-bordered table-advance table-hover" id="users">
            <thead>
            <tr>
                <th>ID</th>
                <th>Surname</th>
                <th>Name</th>
                <th>Patronymic</th>
                <th>City</th>
                <th>Role</th>
                <th class="span3">Actions</th>
            </tr>
            </thead>
            <tfoot>
            <tr>
                <td colspan="6">
                    <a class="btn green" href="<?=$this->url('user/add')?>">
                        <i class="icon-plus-sign icon-white"></i>
                        Add User
                    </a>
                </td>
            </tr>
            </tfoot>
            <tbody>
            <? foreach($users as $user): ?>
                <tr>
                    <td><?=$user->getId()?></td>
                    <td><?=$user->getSurname()?></td>
                    <td><?=$user->getName()?></td>
                    <td><?=$user->getPatronymic()?></td>
                    <td><?=$user->getCity() ? $user->getCity()->getName() : ''?></td>
                    <td><?=implode(', ', $user->getRoles())?></td>
                    <td>
                        <a class="btn blue" href="<?=$this->url('user/edit', array('id' => $user->getId()))?>">
                            <i class="icon-edit"></i>
                            Edit
                        </a>
                        <a onclick="return confirm('Really?')" class="btn red" href="<?=$this->url('user/delete', array('id' => $user->getId()))?>">
                            <i class="icon-minus-sign icon-white"></i>
                            Delete
                        </a>
                    </td>
                </tr>
            <? endforeach; ?>
            </tbody>
        </table>
    </div>
</div>


<? $this->headLink()->appendStylesheet($this->basePath('assets/data-tables/DT_bootstrap.css')) ?>
<? $this->headScript()->appendFile($this->basePath('assets/data-tables/jquery.dataTables.js')) ?>
<? $this->headScript()->appendFile($this->basePath('assets/data-tables/DT_bootstrap.js')) ?>
<? $this->headScript()->appendFile($this->basePath('js/jquery/data-tables/datatables.js')) ?>

<? $this->headScript()->captureStart() ?>
//<script type="text/javascript">
    (function() {
        $('#users').dataTable();
    })();
    //</script>
<? $this->headScript()->captureEnd() ?>
